# 1. Aşama: Build (Derleme)
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# 2. Aşama: Çalıştırma (Serve)
FROM node:18-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/build ./build

EXPOSE 5000
CMD ["serve", "-s", "build", "-l", "5000"]